spring:
  application:
    name: cookbook
  mongodb:
    username: ${MONGODB_USERNAME}
    password: ${MONGODB_PASSWORD}
    uri: mongodb://localhost:27017/${MONGODB_DB_NAME}

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 24 часа в миллисекундах